# This is a comment
# Each line is a file pattern followed by one or more owners

# These owners will be default owners for everything in 
# the repo. Unless a later match takes precedence
# @hopeswiller and @fymagogo will be requested for 
# review when someone opens a pull request
# *      @hopeswiller @fymagogo

theme: jekyll-theme-minimal